In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


None


# Introduction To Tensors

### Creating Tensors
PyTorch tensors are created using 'torch.tensor()'

In [5]:
 # scalar
scalar = torch.tensor(2)
scalar

tensor(2)

In [6]:
# checking dimension
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

2

In [8]:
# Vector
vector = torch.tensor([2, 5])
vector

tensor([2, 5])

In [9]:
# Checking dimension
vector.ndim

1

In [10]:
# shape of the vector
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[2, 3], 
                      [5, 6]])
matrix

tensor([[2, 3],
        [5, 6]])

In [12]:
# checking dimension
matrix.ndim

2

In [13]:
# shape
matrix.shape

torch.Size([2, 2])

In [14]:
# matrix indexing
matrix[0]

tensor([2, 3])

In [15]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                       [6, 7, 7],
                       [10, 11, 12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 6,  7,  7],
         [10, 11, 12]]])

In [16]:
# checking dimension
tensor.ndim

3

In [17]:
# shape
tensor.shape

torch.Size([1, 3, 3])

In [21]:
# tensor indexing
tensor[0]

tensor([[ 1,  2,  3],
        [ 6,  7,  7],
        [10, 11, 12]])

In [22]:
tensor[0][1]

tensor([6, 7, 7])

#### Random tensors

Random tensors are important because the way many neural networks learn is that they start with with tensors
full of random numbers and then adjust those random numbers to better represent the data.

In [48]:
# Create a random tensor of size (2, 5, 3)
random_tensor = torch.rand(2, 5, 3)
random_tensor

tensor([[[0.3031, 0.9210, 0.7400],
         [0.8447, 0.9249, 0.4702],
         [0.3507, 0.6493, 0.1117],
         [0.2942, 0.2393, 0.3331],
         [0.0157, 0.8005, 0.6816]],

        [[0.8647, 0.4802, 0.8595],
         [0.4945, 0.8457, 0.6207],
         [0.3291, 0.9635, 0.8396],
         [0.3886, 0.1871, 0.5209],
         [0.2292, 0.6064, 0.7842]]])

In [51]:
random_tensor.ndim, random_tensor.shape

(3, torch.Size([2, 5, 3]))

In [54]:
# Create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(3, 224, 224))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

#### Zeroes and Ones

In [56]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [57]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [58]:
ones.dtype

torch.float32