In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cpu


# Introduction To Tensors

### Creating Tensors
PyTorch tensors are created using 'torch.tensor()'

In [5]:
 # scalar
scalar = torch.tensor(2)
scalar

tensor(2)

In [6]:
# checking dimension
scalar.ndim

0

In [7]:
# Get tensor back as python int
scalar.item()

2

In [8]:
# Vector
vector = torch.tensor([2, 5])
vector

tensor([2, 5])

In [9]:
# Checking dimension
vector.ndim

1

In [10]:
# shape of the vector
vector.shape

torch.Size([2])

In [11]:
# Matrix
matrix = torch.tensor([[2, 3], 
                      [5, 6]])
matrix

tensor([[2, 3],
        [5, 6]])

In [12]:
# checking dimension
matrix.ndim

2

In [13]:
# shape
matrix.shape

torch.Size([2, 2])

In [14]:
# matrix indexing
matrix[0]

tensor([2, 3])

In [15]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                       [6, 7, 7],
                       [10, 11, 12]]])
tensor

tensor([[[ 1,  2,  3],
         [ 6,  7,  7],
         [10, 11, 12]]])

In [16]:
# checking dimension
tensor.ndim

3

In [17]:
# shape
tensor.shape

torch.Size([1, 3, 3])

In [21]:
# tensor indexing
tensor[0]

tensor([[ 1,  2,  3],
        [ 6,  7,  7],
        [10, 11, 12]])

In [22]:
tensor[0][1]

tensor([6, 7, 7])